from src.domain.generation.value_objects.course_level import CourseLevel
from src.domain.shared.exceptions.validation_error import ValidationError


class GenerationRequest:
    """The input a user sends to trigger course generation.

    Unlike `CourseSource` (which is used for the extraction pipeline),
    this object captures the *specification* of the course to be
    generated by the LLM — no pre-existing content is required.
    """

    def __init__(
        self,
        topic: str,
        course_title: str,
        level: CourseLevel,
        *,
        description: str | None = None,
        target_audience: str | None = None,
        learning_objectives: list[str] | None = None,
        considerations: str | None = None,
        subtopics: list[str] | None = None,
    ):
        self.topic = topic.strip()
        self.course_title = course_title.strip()
        self.level = level
        self.description = description.strip() if description else None
        self.target_audience = (
            target_audience.strip() if target_audience else None
        )
        self.learning_objectives = list(learning_objectives) if learning_objectives else []
        self.considerations = considerations.strip() if considerations else None
        self.subtopics = [s.strip() for s in subtopics] if subtopics else []
        self._validate()

    def _validate(self) -> None:
        if not self.topic:
            raise ValidationError("topic cannot be empty.")
        if not self.course_title:
            raise ValidationError("course_title cannot be empty.")
        if not isinstance(self.level, CourseLevel):
            raise ValidationError(
                f"level must be a CourseLevel, got {type(self.level).__name__}."
            )
        if any(not s for s in self.subtopics):
            raise ValidationError("subtopics cannot contain empty strings.")

    def to_dict(self) -> dict:
        return {
            "topic": self.topic,
            "course_title": self.course_title,
            "level": self.level.value,
            "description": self.description,
            "target_audience": self.target_audience,
            "learning_objectives": self.learning_objectives,
            "considerations": self.considerations,
            "subtopics": self.subtopics,
        }
