"""initial schema

Revision ID: d3819966c2dc
Revises: 
Create Date: 2026-06-02 12:20:58.279943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3819966c2dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_title'), ['title'], unique=False)

    op.create_table('modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_modules_course_id_order', ['course_id', 'order'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_module_id'), ['module_id'], unique=False)
        batch_op.create_index('ix_topics_module_id_order', ['module_id', 'order'], unique=False)

    op.create_table('content_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_blocks_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_content_blocks_topic_id_order', ['topic_id', 'order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_content_blocks_topic_id_order')
        batch_op.drop_index(batch_op.f('ix_content_blocks_topic_id'))

    op.drop_table('content_blocks')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('ix_topics_module_id_order')
        batch_op.drop_index(batch_op.f('ix_topics_module_id'))

    op.drop_table('topics')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index('ix_modules_course_id_order')
        batch_op.drop_index(batch_op.f('ix_modules_course_id'))

    op.drop_table('modules')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_title'))

    op.drop_table('courses')
    # ### end Alembic commands ###
